name: CICD

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_KEY: ${{secrets.DOCKERHUB_KEY}}
  IMAGE_NAME: heron-api-server

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{env.DOCKER_HUB_USERNAME}}
          password: ${{env.DOCKER_KEY}}

      - name: Build Docker Image
        run: docker build -t ${{env.DOCKER_HUB_USERNAME}}/${{env.IMAGE_NAME}}:${{github.sha}} .

      - name: Push Docker Image
        run: docker push ${{env.DOCKER_HUB_USERNAME}}/${{env.IMAGE_NAME}}:${{github.sha}}

  modifyGit:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        name: changing heron-redux helm
        with:
          repository: 'Step-henC/heron-redux'
      - name: modify env
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'actions@github.com'
          pwd
          cd heron-helm
          pwd
          cat values.yaml
          sed -i 's|SERVER_VERSION:.*|SERVER_VERSION: '${{github.sha}}'|' values.yaml
          cat values.yaml
          git add .
          git commit -m "Done by Github Actions"
          git push origin main
